config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root to: "sofas#index"

  resources :users, except: [:edit, :destroy, :update, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :sofas
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :user
	has_many :sofas
end

app/models/sofa.rb
class Sofa < ApplicationRecord

	belongs_to :customer

	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	
	scope :style_family, -> (style_family) { where style_family: style_family }
  	scope :configuration, -> (configuration) { where configuration: configuration }
	scope :fabric_type, -> (fabric_type) { where fabric_type: fabric_type }
  	scope :fabric_style, -> (fabric_style) { where fabric_style: fabric_style }
	scope :leg_style, -> (leg_style) { where leg_style: leg_style }
  	scope :customer_id, -> (customer_id) { where customer_id: customer_id }



  	def self.sofa_families
  		families_array = []
  		Sofa.all.each {|sofa| families_array << sofa.style_family.capitalize}
  		families_array.uniq
  	end

  	def self.sofa_configuration
  		configuration_array = []
  		Sofa.all.each {|sofa| configuration_array << sofa.configuration.capitalize}
  		configuration_array.uniq
  	end

  	def self.sofa_fabric_type
  		fabric_type = []
  		Sofa.all.each {|sofa| fabric_type << sofa.fabric_type.capitalize}
  		fabric_type.uniq
  	end

    def self.sofa_fabric_style
      fabric_style = []
      Sofa.all.each {|sofa| fabric_style << sofa.fabric_style.capitalize}
      fabric_style.uniq
    end

    def self.sofa_leg_style
      leg_style = []
      Sofa.all.each {|sofa| leg_style << sofa.leg_style.capitalize}
      leg_style.uniq
    end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :customers


	validates_presence_of :email, :first_name, :last_name, :password

	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
	protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController


	def new
		@customer = Customer.new
	end

	def create
		if logged_in?
			@customer = Customer.new(customer_params)
			@customer.update_attributes(user_id: current_user.id)
			if @customer.save
				redirect_to root_path, notice: "Customer successfully created."
			end
			render :new
		end
	end


  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: params[:login][:email])
    if @user && @user.authenticate(params[:login][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @error = ["Email and password combination not found."]
      render new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def sesh_params
    params.permit(:email,:password)
  end
end

app/controllers/sofas_controller.rb
class SofasController < ApplicationController
skip_before_action :verify_authenticity_token

	def homeindex
		@sofa = Sofa.all
		# @sofa_families = sofa_families
	end

	def new 
		@sofa = Sofa.new
	end

	def index
	  @sofa_families = Sofa.sofa_families
	  @sofa_configuration = Sofa.sofa_configuration
	  @sofa_fabric_type = Sofa.sofa_fabric_type
	  @sofa_fabric_style = Sofa.sofa_fabric_style
	  @sofa_leg_style = Sofa.sofa_leg_style
	  
	  @sofa = Sofa.where(nil)
	  filtering_params(params).each do |key, value|
		@sofa = @sofa.public_send(key, value.downcase) if value.present? && value != 'Any'
	  end
	end

	def create
		p sofa_params
		if logged_in?
			@sofa = Sofa.new(sofa_params)
			if @sofa.save
				redirect_to root_path, notice: "Sofa successfully created."
			else
				render :new
			end
		end

	end

	private

	def filtering_params(params)
	  params.slice(:style_family, :configuration, :fabric_type, :fabric_style, :leg_style, :customer_id)
	end

	def sofa_params
		params.require(:sofa).permit(:avatar, :style_family, :configuration, :fabric_type, :fabric_style, :leg_style, :customer_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "User successfully created."
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:user_id] != nil
  end

  def current_user
    @_cached_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
  <%= f.label :first_name  %>
  <%= f.text_field :first_name  %><br>

  <%= f.label :last_name  %>
  <%= f.text_field :last_name  %><br>


  <%= f.submit "Create New Customer" %>
<% end %>

app/views/customers/new.html.erb
<%= render partial: '/errors', locals: { object: @customer } %>
<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SofaShowroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </head>

  	<ul id="nav">
  		<%= link_to "Sofa Supply", root_path, class: "navbar-brand" %>
  		<% if logged_in? %>
  			<li class="nav-list"><%= button_to "Log Out", session_path(current_user.id), :method=>:delete, :class=>:destroy %></li>
	  		<li class="nav-list"><%= link_to "Add Sofa", new_sofa_path%></li>
	  		<li class="nav-list"><%= current_user.email%></li>
  		<% else %>
	  		<li class="nav-list"><%= link_to "Register", new_user_path %></li>
	  		<li class="nav-list"><%= link_to "Log In", new_session_path %></li>
	  		
  		<% end %>
	</ul>

  <body class="content">
    <%= yield %>
  </body>
</html>

app/views/sofas/homeindex.html.erb
<div id="sofa-filter">
<h3>Find a Sofa</h3>
</div>
<div class="grid-container">
	<h2>Welcome to Sofa-Showroom </h2>


	<% if @sofa %>
		<div class="grid">
		  <% @sofa.each_slice(3)  do |sofa_group| %>
		    <div class="row">
		    <% sofa_group.each  do |sofa_info| %>
		      <div class="col-sm-6 col-lg-4">
					<figure class="card">
						<img class="card-img" src=<%=sofa_info.avatar.url(:medium)%> alt="Sofa Image Not Found">
						    <figcaption>
						        	<p><%= sofa_info.style_family.capitalize %>, <%= sofa_info.configuration.capitalize %>, <%= sofa_info.fabric_type.capitalize %>, <%= sofa_info.fabric_style.capitalize %>, <%= sofa_info.leg_style.capitalize %></p>
					      </figcaption>
					</figure>
		      </div>
		    <% end %>
		    </div>
		  <% end %>
		</div>
	<% end %>
</div>

app/views/sofas/index.html.erb
<div id="sofa-filter">
	<h5>Find a Sofa Image</h5>
	<%= form_tag '', :method => :get do %>
	  <%= label_tag 'Style_Family'%>
	  <%= select_tag 'style_family', options_for_select(@sofa_families.unshift('Any'))%>
	  <%= label_tag 'Configuration'%>
	  <%= select_tag 'configuration', options_for_select(@sofa_configuration.unshift('Any'))%>
	  <%= label_tag 'Fabric_Type'%>
	  <%= select_tag 'fabric_type', options_for_select(@sofa_fabric_type.unshift('Any'))%>
	  <%= label_tag 'Fabric_Style'%>
	  <%= select_tag 'fabric_style', options_for_select(@sofa_fabric_style.unshift('Any'))%>
	  <%= label_tag 'Leg_Style'%>
	  <%= select_tag 'leg_style', options_for_select(@sofa_leg_style.unshift('Any'))%>
	  <%= submit_tag 'Filter', name: nil %>
	<% end %>
</div>



<div class="grid-container">
	<h2>Welcome to Sofa-Showroom </h2>


	<% if @sofa %>
		<div class="grid">
		  <% @sofa.each_slice(3)  do |sofa_group| %>
		    <div class="row">
		    <% sofa_group.each  do |sofa_info| %>
		      <div class="col-sm-6 col-lg-4">
					<figure class="card">
						<img class="card-img" src=<%=sofa_info.avatar.url(:medium)%> alt="Sofa Image Not Found">
						    <figcaption>
						        	<p><%= sofa_info.style_family.capitalize %>, <%= sofa_info.configuration.capitalize %>, <%= sofa_info.fabric_type.capitalize %>, <%= sofa_info.fabric_style.capitalize %>, <%= sofa_info.leg_style.capitalize %></p>
					      </figcaption>
					</figure>
		      </div>
		    <% end %>
		    </div>
		  <% end %>
		</div>
	<% end %>
</div>

app/views/sofas/new.html.erb
<%= render partial: '/errors', locals: { object: @sofa } %>
<%= form_for @sofa, url: sofas_path, html: { multipart: true } do |f| %>
  <%= f.label :Style_Family  %>
  <%= f.text_field :style_family  %><br>

  <%= f.label :Configuration %>
  <%= f.text_field :configuration  %><br>

  <%= f.label :Fabric_Type %>
  <%= f.text_field :fabric_type  %><br>

  <%= f.label :fabric_style %>
  <%= f.text_field :fabric_style  %><br>

  <%= f.label :leg_style %>
  <%= f.text_field :leg_style  %><br>

  <%= f.label :customer_id_default_1 %>
  <%= f.text_field :customer_id  %><br>

  <%= f.file_field :avatar %>

  <%= f.submit "Create New Sofa" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :first_name  %>
  <%= f.text_field :first_name  %><br>

  <%= f.label :last_name  %>
  <%= f.text_field :last_name  %><br>

  <%= f.label :email  %>
  <%= f.email_field :email  %><br>

  <%= f.label :password  %>
  <%= f.password_field :password  %><br>


  <%= f.submit "Register" %>
<% end %>

app/views/users/new.html.erb
<h4 class="page-header login-header">Register</h4>
<%= render partial: '/errors', locals: { object: @user } %>
<%= render 'form'%>